apiVersion: v1
kind: Pod
metadata:
  name: myconsul-app-client
spec:
  volumes:
  - name: shared-logs 
    emptyDir: {}
  
  containers:
  - name: myconsul-client
    image: docker.io/incrediblehulk/consul-client-new 
    ports:
    - containerPort: 7080
      name: myconsul-client
    - containerPort: 8500
      name: ui-port
    - containerPort: 8400
      name: alt-port
    - containerPort: 53
      name: udp-port
    - containerPort: 8443
      name: https-port
    - containerPort: 8080
      name: http-port
    - containerPort: 8301
      name: serflan
    - containerPort: 8302
      name: serfwan
    - containerPort: 8600
      name: consuldns
    - containerPort: 8300
      name: server
    - containerPort: 8000
      name: watch
    
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log

  - name: myconsul-app
    image: docker.io/incrediblehulk/ubuntu-app
    ports:
    - containerPort: 80
    ports:
    - containerPort: 6080
    
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/ubuntu 

---
apiVersion: v1
kind: Service
metadata:
  name: myconsul-app-client
  namespace: default
  labels:
    app: myconsul-app-client
spec:
  ports:
  - name: myconsul-client
    port: 7080
    protocol: TCP
    targetPort: 7080
  - name: http
    port: 8500
    targetPort: 8500
  - name: https
    port: 8443
    targetPort: 8443
  - name: rpc
    port: 8400
    targetPort: 8400
  - name: serflan-tcp
    protocol: "TCP"
    port: 8301
    targetPort: 8301
  - name: serflan-udp
    protocol: "UDP"
    port: 8301
    targetPort: 8301
  - name: serfwan-tcp
    protocol: "TCP"
    port: 8302
    targetPort: 8302
  - name: serfwan-udp
    protocol: "UDP"
    port: 8302
    targetPort: 8302
  - name: server
    port: 8300
    targetPort: 8300
  - name: consuldns
    port: 8600
    targetPort: 8600
  - name: watch
    port: 8000
    targetPort: 8000
  - name: myconsul-app
    port: 6080
    targetPort: 6080
  selector:
    app: myconsul-app-client
  type: ClusterIP
